### ISSUE TITLE
Adopt pam-auth-update on Ubuntu

### ISSUE THREAD

**Issue by kfiresmith** [ansible-lockdown/UBUNTU20-STIG#58]
## Feature Request or Enhancement

- Enhancement 

**Summary of Request**

Not totally sure if this is more of a RFE or a bug, as the code wasn't working for my systems for 010072, and if it had, it would have broken the official OS method for managing pam.d file contents...

We should adopt pam-auth-update to manage pam.d content changes instead of using fiddly logic and the IMO overly complex Ansible pam module.  My rationale for this is that the official method for managing pam.d configs in Ubuntu is to use pam-auth-update, which will detect any external changes to pam configs, and if it does encounter them, changes requested via pam-auth-update will be rejected without using the `--force` switch which should be avoided in general.
Please check out the contents of /usr/share/pam-configs.  An additional resource would be https://wiki.ubuntu.com/PAMConfigFrameworkSpec.

The upside is that at least for pam_faillock, this should be a very easy change, as the pam-configs are already defined and bundled with the OS-provided pam-auth-update tool so it'd simply be a matter of using them like so:
`pam-auth-update --package --enable faillockmain`.  Here's an example I wrote for duo auth:

```yaml
    - name: Read the contents of /etc/pam.d/common-auth
      ansible.builtin.slurp:
        path: /etc/pam.d/common-auth
      register: common_auth_file
      tags:
        - config
        - pam
        - pam_duo

    - name: Run pam-auth-update only if '/usr/lib64/security/pam_duo.so' is not present
      ansible.builtin.command:
        cmd: /usr/sbin/pam-auth-update --package --enable duo --force
      when: "'/usr/lib64/security/pam_duo.so' not in common_auth_file.content | b64decode"
```

**Describe Alternatives You've Considered**
Current solution, other methods of managing content in pam.d

**Suggested Code**
pam_faillock.yaml:
```yaml
---
  
- name: "LOW | UBTU-20-010072 | PATCH | The Ubuntu operating system must automatically lock an account until the locked account is released by an administrator when three unsuccessful logon attempts have been made."
  block:
    - name: Install pam-config profiles using a loop
      ansible.builtin.template:
        src: "pam-configs/pam-configs-profile-{{ item }}.j2"
        dest: "/usr/share/pam-configs/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - faillockmain
        - faillockpost
        - faillockpre

    - name: Read the contents of /etc/pam.d/common-auth
      ansible.builtin.slurp:
        path: /etc/pam.d/common-auth
      register: common_auth_file

    - name: Run pam-auth-config enable for faillockpre only if 'required pam_faillock.so preauth' is not present
      ansible.builtin.command:
        cmd: /usr/sbin/pam-auth-update --package --enable faillockpre --force
      when: "'required pam_faillock.so preauth' not in common_auth_file.content | b64decode"

    - name: Run pam-auth-config enable for faillockmain only if '[default=die] pam_faillock.so authfail' is not present
      ansible.builtin.command:
        cmd: /usr/sbin/pam-auth-update --package --enable faillockmain --force
      when: "'[default=die] pam_faillock.so authfail' not in common_auth_file.content | b64decode"

    - name: Run pam-auth-config enable for faillockpost only if 'sufficient pam_faillock.so authsucc' is not present
      ansible.builtin.command:
        cmd: /usr/sbin/pam-auth-update --package --enable faillockpost --force
      when: "'sufficient pam_faillock.so authsucc' not in common_auth_file.content | b64decode"

  tags:
    - pam
    - pamd
    - UBTU-20-010072
    - CAT3
    - CCI-000044
    - CCI-002238
    - SRG-OS-000329-GPOS-00128
    - SV-238235r853414_rule
    - V-238235
```
Templates called:
pam-configs-profile-faillockmain.j2
```
{#
This is a pam-auth-update profile that will install a pam_faillock.so authfail
line into /etc/pam.d/common-auth.
#}
Name: Faillock Main
Default: no
Priority: 64

Auth-Type: Primary
Auth:
        [default=die] pam_faillock.so authfail
```
pam-configs-profile-faillockpost.j2
```
{#
This is a pam-auth-update profile that will install a pam_faillock.so authsucc
line into /etc/pam.d/common-auth.
#}
Name: Faillock Authsucc
Default: no
Priority: 128

Auth-Type: Additional
Auth:
        sufficient pam_faillock.so authsucc
```
pam-configs-profile-faillockpre.j2
```
{#
This is a pam-auth-update profile that will install a pam_faillock.so preauth
line into /etc/pam.d/common-auth.
#}
Name: Faillock Preauth
Default: no
Priority: 384

Auth-Type: Primary
Auth:
        required pam_faillock.so preauth
```
